name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.4.1
        with:
          node-version: 12.x
      - run: |
          npm run all
      - name: Verify no unstaged changes
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
            git status
            echo "::error::Unstaged changes detected. Run 'npm run all' before commit"
            exit 1
          fi
  test: # make sure the action works on a clean machine without building
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - id: npm-audit-pr
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
